version: "3.8"
services:
  backend:
    build: ./docker/server
    volumes:
      - ./server:/app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=user
      - DB_PASSWORD=pwd
      - DB_NAME=mydb
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - MYSQL_ROOT_PASSWORD=pwdroot
    ports:
      - "3306:3306"